name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Upgrade pip
        run: python -m pip install -U pip
      - name: Install dev dependencies
        run: |
          pip install -r requirements-dev.txt || true
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Validate YAML indexes (videos/books)
        run: |
          pip install pyyaml
          pytest -q tests/test_videos_index.py || true
          pytest -q tests/test_books_index.py  || true
      - name: Ruff (lint)
        run: ruff check src tests
      - name: Black (format check)
        run: black --check src tests
      - name: Unit tests
        run: pytest -q
